"""
Newsletter workflow UI.

Single Flask app driving the full issue workflow: fetch (cached) -> select
movies -> organize into sections + comment -> prerender -> validate.
Run from the repo root: python viewer.py
"""
import json
import os

from flask import Flask, render_template, jsonify, request, send_file

from pipeline.runner import pipeline, get_cache_info
from pipeline import issue as issue_store
from pipeline import prerender as prerender_mod
from pipeline import validation as validation_mod
from pipeline.analysis import get_normalized_score

app = Flask(__name__)

# Category display names and descriptions (browsing lenses over the scrape)
CATEGORIES = {
    "top_new_releases": {
        "name": "Top New Releases",
        "description": "Brand new movies released within the last 7 days"
    },
    "current_landscape": {
        "name": "Current Landscape",
        "description": "Recent movies still playing in theaters (1-8 weeks old)"
    },
    "premieres_events": {
        "name": "Premieres & Events",
        "description": "Special premiere screenings and events"
    },
    "old_classics": {
        "name": "Old Classics",
        "description": "Classic films returning to the big screen"
    },
    "letterboxd_picks": {
        "name": "Letterboxd Picks",
        "description": "Highly rated on Letterboxd (7.0+)"
    },
    "niche_gems": {
        "name": "Niche Gems",
        "description": "High quality films with limited screenings"
    }
}


def load_categorized() -> dict:
    """Newsletter categories generated by the analysis step."""
    try:
        with open('data/newsletter_data.json', 'r', encoding='utf-8') as f:
            return json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        return {}


def load_all_movies() -> list:
    """Every scraped movie, scored and sorted, for the 'All movies' tab."""
    try:
        with open('data/week_full.json', 'r', encoding='utf-8') as f:
            movies = json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        return []
    for m in movies:
        m['calculated_score'] = get_normalized_score(m)
    movies.sort(key=lambda m: m['calculated_score'], reverse=True)
    return movies


def build_select_movies() -> list:
    """Slim, deduplicated movie list for the selection UI.

    Each movie appears once, tagged with every category it belongs to,
    so the client can filter without showing duplicates.
    """
    categorized = load_categorized()
    membership = {}
    for key in CATEGORIES:
        for m in categorized.get(key, []):
            membership.setdefault(str(m['id']), []).append(key)

    slim = []
    for m in load_all_movies():
        mid = str(m['id'])
        slim.append({
            "id": mid,
            "title": m['title'],
            "original_title": m.get('original_title') or "",
            "director": m.get('director') or "",
            "actors": m.get('actors') or "",
            "year": m.get('year'),
            "genre": m.get('genre') or "",
            "duration": m.get('duration_minutes'),
            "copies": m.get('copies_count') or 0,
            "showtimes": len(m.get('showtimes') or []),
            "poster_url": m.get('poster_url'),
            "score": m['calculated_score'],
            "ratings": [{"s": r['source'], "v": r['score'], "m": r['max_score']}
                        for r in m.get('ratings', [])],
            "cats": membership.get(mid, []),
            "release_date": m.get('release_date'),
            "premiere": bool(m.get('is_premiere')),
            "new_release": bool(m.get('is_new_release')),
        })
    return slim


@app.route('/')
def index():
    return render_template(
        'viewer.html',
        select_movies=build_select_movies(),
        categories=CATEGORIES,
        sections=issue_store.load_sections(),
        issue=issue_store.load_issue(),
        cache=get_cache_info()
    )


# ---- Pipeline (fetch with cache) ----

@app.route('/api/pipeline/status')
def pipeline_status():
    state = pipeline.get_state()
    state["cache"] = get_cache_info()
    return jsonify(state)


@app.route('/api/pipeline/fetch', methods=['POST'])
def start_fetch():
    force = bool((request.get_json(silent=True) or {}).get('force'))
    return jsonify(pipeline.run_fetch(force=force))


@app.route('/api/pipeline/reset', methods=['POST'])
def reset_pipeline():
    pipeline.reset()
    return jsonify({"status": "reset"})


# ---- Issue draft ----

@app.route('/api/issue', methods=['PUT'])
def save_issue():
    payload = request.get_json(force=True)
    issue = issue_store.save_issue(
        payload.get('movies', {}),
        content=payload.get('content')
    )
    return jsonify(issue)


# ---- Sections ----

@app.route('/api/sections', methods=['POST'])
def add_section():
    payload = request.get_json(force=True)
    try:
        section = issue_store.add_section(
            payload.get('title', ''), payload.get('description', ''))
    except ValueError as e:
        return jsonify({"error": str(e)}), 400
    return jsonify(section)


@app.route('/api/sections/<key>', methods=['PATCH'])
def update_section(key):
    payload = request.get_json(force=True)
    try:
        section = issue_store.update_section(
            key, payload.get('title'), payload.get('description'))
    except ValueError as e:
        return jsonify({"error": str(e)}), 400
    return jsonify(section)


@app.route('/api/sections/<key>', methods=['DELETE'])
def delete_section(key):
    try:
        issue_store.delete_section(key)
    except ValueError as e:
        return jsonify({"error": str(e)}), 400
    return jsonify({"deleted": key})


# ---- Prerender & validation ----

@app.route('/api/prerender', methods=['POST'])
def run_prerender():
    return jsonify(prerender_mod.run_prerender())


@app.route('/preview')
def preview():
    path = os.path.abspath(prerender_mod.PREVIEW_FILE)
    if not os.path.exists(path):
        return "No preview rendered yet.", 404
    response = send_file(path)
    response.headers['Cache-Control'] = 'no-store'
    return response


@app.route('/api/validate', methods=['POST'])
def validate():
    # Always validate a fresh render of the current draft
    render_result = prerender_mod.run_prerender()
    if not render_result["ok"]:
        return jsonify({"passed": False, "status": "draft", "checks": [],
                        "error": f"Prerender failed: {render_result['log']}"})
    result = validation_mod.run_validation()
    return jsonify(result)


if __name__ == '__main__':
    print("Starting Newsletter Workflow UI...")
    print("Open http://localhost:5000 in your browser")
    app.run(debug=True, port=5000)
