"""
Newsletter workflow UI.

Single Flask app driving the full issue workflow: fetch (cached) -> select
movies -> organize into sections + comment -> prerender -> validate.
Run from the repo root: python viewer.py
"""
import json
import os

from flask import Flask, render_template, jsonify, request, send_file

from pipeline.runner import pipeline, get_cache_info
from pipeline import issue as issue_store
from pipeline import prerender as prerender_mod
from pipeline import validation as validation_mod
from pipeline.analysis import get_normalized_score

app = Flask(__name__)

# Category display names and descriptions (browsing lenses over the scrape)
CATEGORIES = {
    "top_new_releases": {
        "name": "Top New Releases",
        "description": "Brand new movies released within the last 7 days"
    },
    "current_landscape": {
        "name": "Current Landscape",
        "description": "Recent movies still playing in theaters (1-8 weeks old)"
    },
    "premieres_events": {
        "name": "Premieres & Events",
        "description": "Special premiere screenings and events"
    },
    "old_classics": {
        "name": "Old Classics",
        "description": "Classic films returning to the big screen"
    },
    "letterboxd_picks": {
        "name": "Letterboxd Picks",
        "description": "Highly rated on Letterboxd (7.0+)"
    },
    "niche_gems": {
        "name": "Niche Gems",
        "description": "High quality films with limited screenings"
    }
}


def load_categorized() -> dict:
    """Newsletter categories generated by the analysis step."""
    try:
        with open('data/newsletter_data.json', 'r', encoding='utf-8') as f:
            return json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        return {}


def load_all_movies() -> list:
    """Every scraped movie, scored and sorted, for the 'All movies' tab."""
    try:
        with open('data/week_full.json', 'r', encoding='utf-8') as f:
            movies = json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        return []
    for m in movies:
        m['calculated_score'] = get_normalized_score(m)
    movies.sort(key=lambda m: m['calculated_score'], reverse=True)
    return movies


@app.route('/')
def index():
    all_movies = load_all_movies()
    movie_index = {
        str(m['id']): {
            "title": m['title'],
            "year": m.get('year'),
            "poster_url": m.get('poster_url'),
            "score": m['calculated_score']
        }
        for m in all_movies
    }
    return render_template(
        'viewer.html',
        data=load_categorized(),
        all_movies=all_movies,
        categories=CATEGORIES,
        sections=issue_store.load_sections(),
        issue=issue_store.load_issue(),
        cache=get_cache_info(),
        movie_index=movie_index
    )


# ---- Pipeline (fetch with cache) ----

@app.route('/api/pipeline/status')
def pipeline_status():
    state = pipeline.get_state()
    state["cache"] = get_cache_info()
    return jsonify(state)


@app.route('/api/pipeline/fetch', methods=['POST'])
def start_fetch():
    force = bool((request.get_json(silent=True) or {}).get('force'))
    return jsonify(pipeline.run_fetch(force=force))


@app.route('/api/pipeline/reset', methods=['POST'])
def reset_pipeline():
    pipeline.reset()
    return jsonify({"status": "reset"})


# ---- Issue draft ----

@app.route('/api/issue', methods=['PUT'])
def save_issue():
    payload = request.get_json(force=True)
    issue = issue_store.save_issue(payload.get('movies', {}))
    return jsonify(issue)


# ---- Sections ----

@app.route('/api/sections', methods=['POST'])
def add_section():
    payload = request.get_json(force=True)
    try:
        section = issue_store.add_section(
            payload.get('title', ''), payload.get('description', ''))
    except ValueError as e:
        return jsonify({"error": str(e)}), 400
    return jsonify(section)


@app.route('/api/sections/<key>', methods=['DELETE'])
def delete_section(key):
    try:
        issue_store.delete_section(key)
    except ValueError as e:
        return jsonify({"error": str(e)}), 400
    return jsonify({"deleted": key})


# ---- Prerender & validation ----

@app.route('/api/prerender', methods=['POST'])
def run_prerender():
    return jsonify(prerender_mod.run_prerender())


@app.route('/preview')
def preview():
    path = os.path.abspath(prerender_mod.PREVIEW_FILE)
    if not os.path.exists(path):
        return "No preview rendered yet.", 404
    response = send_file(path)
    response.headers['Cache-Control'] = 'no-store'
    return response


@app.route('/api/validate', methods=['POST'])
def validate():
    # Always validate a fresh render of the current draft
    render_result = prerender_mod.run_prerender()
    if not render_result["ok"]:
        return jsonify({"passed": False, "status": "draft", "checks": [],
                        "error": f"Prerender failed: {render_result['log']}"})
    result = validation_mod.run_validation()
    return jsonify(result)


if __name__ == '__main__':
    print("Starting Newsletter Workflow UI...")
    print("Open http://localhost:5000 in your browser")
    app.run(debug=True, port=5000)
